### ISSUE TITLE
.get() cannot return stored non-JSON values

### ISSUE THREAD

**Issue by tbassetto** [grevory/angular-local-storage#230]
I have tried to upgrade from version 0.15 to 0.2.1, but the latest version cannot read value stored with the previous one.

We store a token by using:

```javascript
localStorageService.set('token', newToken); // newToken is just alphanumeric characters
```

And now the following code is crashing:

```javascript
localStorageService.get('token'); // token is just alphanumeric characters
```

I had a look at the code and the issue is that now you always apply [`JSON.parse()`](https://github.com/grevory/angular-local-storage/blob/0466c13b3bb3cecc2cab80c8783ac9b7bc7a83d1/dist/angular-local-storage.js#L184) while before you used to call [`fromJson()` only when it made sense](https://github.com/grevory/angular-local-storage/blob/ae0c28aba9050225a7e3327600307bedd0be8586/dist/angular-local-storage.js#L200).

Is it possible to revert to the previous behavior? Why has this change been made?

**Comment by btesser** [comment]
I have the same problem.  I tracked it down to this code
0.2.0
```
    if (isUndefined(value)) {
        value = null;
  } else if (isObject(value) || isArray(value) || isNumber(+value || value)) {
        value = toJson(value);
      }
```
0.2.1
```
if (isUndefined(value)) {
        value = null;
      } else {
        value = toJson(value);
      }
```

**Comment by a8m** [comment]
Can you please provide some example @tbassetto ?
Please take a look on #225, #222, #214, etc.. if you want to get some point why this changes made for.

Thanks.

**Comment by btesser** [comment]
This sounds like a breaking change that needs to be noted in the changelog.
for example: these key value paris cause an error
![image](https://cloud.githubusercontent.com/assets/830336/7866005/7d2a2030-053a-11e5-9bea-af2c317f706d.png)

**Comment by btesser** [comment]
@a8m please look at examples from previous comment

**Comment by joecode** [comment]
thanks @tbassetto for pointing out the root of the problem and agree with @btesser. while this change certainly makes sense, there should be alarm bells. it got deployed in production before we caught it and now i have to monkey wrench things back into shape with stuff like:

```
if (/^[a-zA-Z0-9]*$/.test(token)) {
    console.log('jsonifying token');
    localStorage['ls.token']=JSON.stringify(token);
  }
```

(of course that only handles the localStorage version, not the cookie based fallback.)

**Comment by a8m** [comment]
Fixed via v0.2.2.
Can you please validate that this issue has been resolved?

**Comment by joecode** [comment]
Doesn't matter for my use case, but if someone was storing quoted strings based on the [old setter function](https://github.com/grevory/angular-local-storage/blob/ae0c28aba9050225a7e3327600307bedd0be8586/dist/angular-local-storage.js#L150), wouldn't this inadvertently remove them? I.e. imagine a "This is a famous quote" stored verbatim as as string.

Seems like a difficult problem to fully solve because there's no telling how people may have used (or abused?) the original verbatim string functionality.

**Comment by neverend92** [comment]
Still not working for me, because the try-catch doesn't seem to work the way it should.
Debugged your code a bit and found following solution for me:

Your old code:
```javascript
try {
   return JSON.parse(item);
} catch (e) {
   return item;
}
```

My fix:
```javascript
try {
   a = JSON.parse(item);
   return a;
} catch (e) {
   return item;
}
```

Because of this the try-catch now seems to work!
